slowfit/models.py
from django.db import models
from django.contrib.auth.models import User
from time import datetime


class BaseModel(models.Model):
	name = models.CharField()
	description = models.TextField()


class Note(models.Model):
    posted  = models.DateTimeField(auto_now_add=True)
	noteFor = models.ForeignKey(BaseModel)
    by      = models.ForeignKey(User)
    text    = models.TextField()


def asset_directory(instance, filename):
	return f"assets/{instance.assetOf.name}"


class Asset(models.Model):
	assetOf     = models.ForeignKey(BaseModel)
	name        = models.CharField()
	description = models.TextField()
	tags        = models.TextField()
	mimeType    = models.TextField()
	asset       = models.FileField(upload_to=asset_directory)


class Country(models.Model):
	name     = models.CharField()
	isoCode  = models.CharField()
	isoCode3 = models.CharField()

    def flag(self, size):
        return f"/image/flags/{size}/{self.isoCode}.png"


class BikeType(BaseModel):
	pass


class Material(BaseModel):
	pass


class Brand(BaseModel):
	country     = models.ForeignKey(Country)
	URL         = models.URLField()
	imported    = models.ForeignKey(ImportLog)


class Frame(BaseModel):
	brand       = models.ForeignKey(Brand)
	bikeType    = models.ForeignKey(BikeType)
	material    = models.ForeignKey(Material)
	URL         = models.URLField()
	yearFrom    = models.PositiveSmallIntegerField()
	yearTo      = models.PositiveSmallIntegerField()
	imported    = models.ForeignKey(ImportLog)


class FrameSize(BaseModel):
	frame       = models.ForeignKey(Frame)
	HTAngle     = models.FloatField()

slowfit/models/fits.py
import datetime

from django.db import models
from django.urls import reverse

from .base import Annotateable
from .base import AssetOwner
from .base import BaseModel
from .bikes import FrameSize


class Customer(BaseModel, AssetOwner, Annotateable):
    class Meta:
        ordering = ['lastName', 'firstName']

    firstName = models.CharField("First Name", max_length=30)
    lastName = models.CharField("Last Name", max_length=30)
    address = models.TextField("Address", null=True, blank=True)
    email = models.EmailField("EMail Address", unique=True, max_length=60)
    phoneMain = models.CharField("Main Phone Number", unique=True, max_length=20)
    phoneAlt = models.CharField("Alternative Phone Number", null=True, max_length=20, blank=True)
    dateOfBirth = models.DateField("Date of Birth", null=True, blank=True)
    height = models.PositiveSmallIntegerField("Height in cm", null=True, blank=True)
    inseam = models.PositiveSmallIntegerField("Inseam in cm", null=True, blank=True)
    armLength = models.PositiveSmallIntegerField("Arm Length in cm", null=True, blank=True)

    @property
    def age(self):
        delta = datetime.date.today() - self.dateOfBirth
        return delta.year

    @property
    def fullname(self):
        return f"{self.firstName} {self.lastName}"

    def get_absolute_url(self):
        return reverse('customer-view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.fullname


CRANK_LENGTH = [
    (165, "165mm"),
    (167.5, "167.5mm"),
    (170, "170mm"),
    (172.5, "172.5mm"),
    (175, "175mm"),
]

PEDAL_SYSTEM = [
    ("Shimano Road", "Shimano Road"),
    ("Shimano SPD", "Shimano SPD"),
    ("Look", "Look"),
    ("Time", "Time"),
    ("Speedplay", "Speedplay"),
]


class Visit(BaseModel, AssetOwner, Annotateable):
    class Meta:
        get_latest_by = "date"
        order_with_respect_to = 'customer'

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateTimeField('Date of Visit')
    purpose = models.CharField("Purpose of Visit", max_length=100, blank=False, null=False)
    experience = models.TextField("Cycling Experience", blank=True, null=True)
    goals = models.TextField("Athletic Goals", blank=True, null=True)
    injuries = models.TextField("Injuries and Limitations", blank=True, null=True)
    weight = models.PositiveSmallIntegerField("Weight in kg", blank=True, null=True)
    customerConcerns = models.TextField("Rider's Specific Concerns", blank=True, null=True)
    fitterConcerns = models.TextField("Fitter's Concerns", blank=True, null=True)
    currentBike = models.ForeignKey(FrameSize, verbose_name="Current Bike", on_delete=models.PROTECT, null=True, blank=True)
    pedalSystem = models.TextField("Pedal System", choices=PEDAL_SYSTEM, null=True, blank=True)
    hx = models.PositiveSmallIntegerField("Current Handlebar Reach (mm)", null=True, blank=True)
    hy = models.PositiveSmallIntegerField("Current Handlebar Stack (mm)", null=True, blank=True)
    sx = models.SmallIntegerField("Current Saddle X", null=True, blank=True)
    sy = models.PositiveSmallIntegerField("Current Saddle Y", null=True, blank=True)
    crankLength = models.PositiveSmallIntegerField("Current Crank Length", choices=CRANK_LENGTH, null=True, blank=True)
    saddle = models.CharField("Current Saddle", blank=True, max_length=30, null=True)
    saddleHeight = models.PositiveSmallIntegerField("Current Saddle Height", null=True, blank=True)
    saddleSetback = models.SmallIntegerField("Current Saddle Setback/Offset", null=True, blank=True)
    saddleBarDrop = models.SmallIntegerField("Current Saddle to Bar drop",
                                             help_text=
                                             "positive: saddle higher than bar, negative: bar higher than saddle",
                                             null=True, blank=True)

    def get_absolute_url(self):
        return reverse('visit-view', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.customer.fullname} - {self.date}: {self.purpose}"


class FitSheet(BaseModel, AssetOwner, Annotateable):
    class Meta:
        order_with_respect_to = 'visit'

    fit_type = None

    visit = models.ForeignKey(Visit, on_delete=models.CASCADE)
    bikeUsed = models.ForeignKey(FrameSize, verbose_name="Bike Used", on_delete=models.PROTECT, blank=True, null=True)
    hx = models.PositiveSmallIntegerField("Selected Handlebar Reach (mm)", blank=True, null=True)
    hy = models.PositiveSmallIntegerField("Selected Handlebar Stack (mm)", blank=True, null=True)
    sx = models.SmallIntegerField("Selected Current Saddle X", blank=True, null=True)
    sy = models.PositiveSmallIntegerField("Selected Current Saddle Y", blank=True, null=True)
    crankLength = models.PositiveSmallIntegerField("Selected Current Crank Length", choices=CRANK_LENGTH, blank=True, null=True)
    saddle = models.CharField("Selected Saddle", blank=True, max_length=30, null=True)
    saddleHeight = models.PositiveSmallIntegerField("Selected Saddle Height", blank=True, null=True)
    saddleSetback = models.SmallIntegerField("Selected Saddle Setback/Offset", blank=True, null=True)
    saddleBarDrop = models.SmallIntegerField("Selected Saddle to Bar Drop",
                                             help_text=
                                             "positive: saddle higher than bar, negative: bar higher than saddle",
                                             blank=True, null=True)


class Trial(BaseModel, AssetOwner, Annotateable):
    class Meta:
        order_with_respect_to = 'fitSheet'

    fitSheet = models.ForeignKey(FitSheet, on_delete=models.CASCADE)
    hx = models.PositiveSmallIntegerField("Handlebar Reach (mm)")
    hy = models.PositiveSmallIntegerField("Handlebar Stack (mm)")
    sx = models.SmallIntegerField("Saddle X")
    sy = models.PositiveSmallIntegerField("Saddle Y")

    def get_absolute_url(self):
        return reverse('fitsheet-view-tab', kwargs={'pk': self.fitSheet.id, 'tab': 'trials'})


class RoadFitSheet(FitSheet):
    fit_type = "Road"
    webX = models.PositiveSmallIntegerField("Selected Handlebar Web X (Reach)", blank=True, null=True)
    webY = models.PositiveSmallIntegerField("Selected Handlebar Web Y (Stack)", blank=True, null=True)
    barWidth = models.PositiveSmallIntegerField("Selected Handlebar Width", blank=True, null=True)
    barDrop = models.PositiveSmallIntegerField("Selected Handlebar Drop", blank=True, null=True)
    barReach = models.PositiveSmallIntegerField("Selected Handlebar Reach", blank=True, null=True)

    def get_absolute_url(self):
        return reverse('fitsheet-view', kwargs={'pk': self.pk})


class TTFitSheet(FitSheet):
    fit_type = "Time Trial/Triathlon"
    aeroBar = models.CharField("Selected Aerobar", blank=True, max_length=30, null=True)
    padWidth = models.PositiveSmallIntegerField("Pad Width (mm)", blank=True, null=True)
    extensions = models.CharField("Selected Extensions", blank=True, max_length=30, null=True)

    def get_absolute_url(self):
        return reverse('fitsheet-view', kwargs={'pk': self.pk})

slowfit/models/imports.py
from django.contrib.auth.models import User
from django.db import models

START = "Start"
BUSY = "Busy"
OK = "Done"
ERRORS = "Errors"
STATUS_CHOICES = [
	(START, START),
	(BUSY, BUSY),
	(OK, OK),
	(ERRORS, ERRORS),
]


class ImportLog(models.Model):
	class Meta:
		ordering = ("-timestamp", )

	timestamp = models.DateTimeField(auto_now_add=True)
	importedBy = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	reference = models.TextField(null=True)
	title = models.TextField(null=True)
	status = models.TextField(choices=STATUS_CHOICES)
	frameCount = models.PositiveSmallIntegerField(default=0)
	log = models.TextField(null=True)

	def log_error(self, fmt, *args):
		msg = fmt.format(*args)
		if msg != "":
			self.log = "{0}{0}\n".format(self.log, msg)
		self.set_status(ERRORS)

	def set_status(self, status):
		self.status = status
		self.save()

slowfit/templates/slowfit/brand_detail.html
{% extends "detail_view.html" %}

slowfit/templates/slowfit/brand_detail_frames.html
<div class="row my-3">
    <div class="col-sm-12">
        <table class="table table-bordered table-hover">
            {% for frame in object.frame_set.all %}
                {% if forloop.first %}
                    <tr>
                        <th class="text-center">Model Year</th>
                        <th class="text-center">Frame</th>
                        <th class="text-center">Type</th>
                        <th class="text-center">Material</th>
                    </tr>
                {% endif %}
                <tr>
                    <td class="text-center"><a href="/year/{{ frame.yearFrom }}">{{ frame.yearFrom }}</a></td>
                    <td class="text-center"><a href="/frame/{{ frame.id }}">{{ frame.name }}</a></td>
                    <td class="text-center"><a href="/type/{{ frame.bikeType.id }}">{{ frame.bikeType.name }}</a></td>
                    <td class="text-center"><a href="/material/{{ frame.material.id }}">{{ frame.material.name }}</a></td>
                </tr>
            {% empty %}
                <tr>
                    <td>
                        <h4>None yet!</h4>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
<div class="row my-3">
    <div class="col-sm-12">
        <a href="/frame/new?brand_id={{ object.id }}&cancelurl="/dev/null"> <!-- FIXME -->
            <button class="btn btn-primary" type="button">
                New Frame
            </button>
        </a>
    </div>
</div>

slowfit/templates/slowfit/brand_list.html
{%  extends "base.html" %}

{% block Title %}Slowfit bike fit tracker - Brands{% endblock Title %}

{% block Body %}
    <div class="row">
        <h2>Brands</h2>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <tr>
                <th class="text-center" style="width: 60px">&nbsp;</th>
                <th class="text-center" style="width: 60px">&nbsp;</th>
                <th class="text-center">Brand</th>
                <th class="text-center">Description</th>
                <th class="text-center">Website</th>
            </tr>
            {% for brand in object_list %}
                <tr>
                    <td class="text-center" style="width: 60px">
                        {% if brand.country and brand.country.isoCode %}
                            <img src="{{ brand.country.flag }}" alt="{{ brand.country.name}}"
                                 height="17px" width="25px"/>
                        {% else %}
                            &nbsp;
                        {% endif %}
                    </td>
                    <td class="text-center" style="width: 60px">
                        {% if brand.logo %}
                            <img height="25px" src="/asset/{{ brand.logo.id }}" alt="{{ brand.name }}"/>
                        {% else %}
                            &nbsp;
                        {% endif %}
                    </td>
                    <td class="text-center" style="vertical-align: middle">
                        <a href="/brand/{{ brand.id }}">{{ brand.name }}</a>
                    </td>
                    <td class="text-center">{{ brand.description }}</td>
                    <td class="text-center" style="vertical-align: middle">{{  brand.URL|urlizetrunc:30 }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5"><i>No brands yet</i></td>
                </tr>
            {% endfor %}
        </table>
        <a class="btn btn-primary" href="/brand/new">
            New Brand
        </a>
    </div>
{% endblock Body %}

slowfit/templates/slowfit/customer_detail_profile.html
{% load field %}

<div class="card">
    <div class="card-body">
        {% field object "firstName" mode %}
        {% field object "lastName" mode %}
        {% field object "address" mode %}
        {% field object "email" mode %}
        {% field object "phoneMain" mode %}
        {% field object "phoneAlt" mode %}
        {% field object "dateOfBirth" mode %}
        {% field object "height" mode %}
        {% field object "inseam" mode %}
        <div class="row my-3">
            <div class="col-sm">
                <a href="{% url editurl object.id %}" id="customer-edit-link" class="btn btn-primary">Edit</a>
            </div>
        </div>
    </div>
</div>

slowfit/templates/slowfit/customer_edit.html
{% extends "detail_form.html" %}

{% block Title %}
    {{ object.fullname }}
{% endblock %}

{% block HeaderText %}
    {{ object.fullname }}
{% endblock %}

slowfit/templates/slowfit/customer_list.html
{%  extends "base.html" %}

{% block Title %}Slowfit bike fit tracker - Customers{% endblock Title %}

{% block Body %}
    <div class="row">
        <h2 id="customers_header">Customers</h2>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <tr>
                <th class="text-center">First Name</th>
                <th class="text-center">Last Name</th>
            </tr>
            {% for customer in object_list %}
                <tr>
                    <td class="text-center">
                        <a href="{% url 'customer-view' customer.id %}" id="firstName-link-{{ customer.id }}">{{ customer.firstName }}</a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'customer-view' customer.id %}" id="lastName-link-{{ customer.id }}">{{ customer.lastName }}</a>
                    </td>
                </tr>
                {% if forloop.last %}
                <tr id="new-size">
                    <td>&nbsp;</td>
                {% endif %}
            {% empty %}
                <tr id="new-size">
                    <td>None yet!</td>
            {% endfor %}
                    <td class="text-center">
                        <a href="{% url 'customer-new' %}" class="btn btn-primary" id="new_customer_link">New Customer</a>
                    </td>
                </tr>
        </table>
    </div>
{% endblock %}

slowfit/templates/slowfit/customer_new.html
{% extends "detail_form.html" %}

{% block Title %}
    New Customer
{% endblock %}

{% block HeaderText %}
    New Customer
{% endblock %}

slowfit/templates/slowfit/fitsheet_detail_details.html
{% load field %}

<div class="card">
    <div class="card-body">
        {% field object "description" mode %}
        {% field object "hy" mode %}
        {% field object "hx" mode %}
        {{ model }}
        {% if model == "roadfitsheet" %}
            {% field object "webY" mode %}
            {% field object "webX" mode %}
        {% endif %}
        {% field object "sy" mode %}
        {% field object "sx" mode %}
        {% field object "crankLength" mode %}
        {% field object "saddle" mode %}
        {% field object "saddleHeight" mode %}
        {% field object "saddleSetback" mode %}
        {% field object "saddleBarDrop" mode %}
        {% if model == "roadfitsheet" %}
            {% field object "barWidth" mode %}
            {% field object "barDrop" mode %}
            {% field object "barReach" mode %}
        {% else %}
            {% field object "aeroBar" mode %}
            {% field object "padWidth" mode %}
            {% field object "extensions" mode %}
        {% endif %}


        <div class="row my-3">
            <div class="col-sm">
                <a href="{% url editurl object.id %}" class="btn btn-primary">Edit</a>
            </div>
        </div>
    </div>
</div>

slowfit/templates/slowfit/fitsheet_detail_trials.html
<script>
    let rowIx = -1;
    let active_form = null;
    let active_row = null;
    let view_row = null;
    let new_button_row = null;

    function _cancel() {
        if (!new_button_row) {
            new_button_row = document.getElementById("new_trial")
        }
        if (active_form) {
            active_form.reset();
            active_form = null;
        }
        if (active_row) {
            active_row.hidden = true;
            active_row = null;
        }
        if (view_row) {
            view_row.hidden = false;
            view_row = null;
        }
        new_button_row.hidden = false;
    }

    function _activate(form, edit, view) {
        if (!new_button_row) {
            new_button_row = document.getElementById("new_trial")
        }
        _cancel()
        active_form = form;
        active_row = edit;
        view_row = view;
        if (view) {
            view.hidden = true;
        }
        if (edit) {
            edit.hidden = false;
        }
        new_button_row.hidden = true;
    }

    function doNewTrial() {
        _activate(document.getElementById("Trial-New-form"),
            document.getElementById("Trial-New"), null);
    }

    function doConfirmDeleteTrial(trial_id, trial_count) {
        if (window.confirm(`Are you sure you want to delete trial ${trial_count}?`)) {
            const form = document.getElementById(`Trial-${id}-delete`);
            form.submit();
        }
    }

    function doCancelNewTrial() {
        _cancel();
    }

    function doEditTrial(id) {
        _activate(document.getElementById(`Trial-${id}-form`),
            document.getElementById(`Trial-${id}-Edit`),
            document.getElementById(`Trial-${id}-View`))
    }

    function doCancelEditTrial() {
        _cancel()
    }
</script>

<div class="row my-3">
    <div class="col-sm-12">
        <table class="table table-bordered table-hover">
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">HY (Stack)</th>
                <th class="text-center">HX (Reach)</th>
                <th class="text-center">SY (Saddle Vert)</th>
                <th class="text-center">HX (Saddle Horiz)</th>
                <th class="text-center">&nbsp;</th>
            </tr>
            {% for trial in object.trial_set.all %}
                <tr id="Trial-{{ trial.id }}-View">
                    <td class="text-center">{{ forloop.counter }}</td>
                    <td class="text-center">{{ trial.hy }}</td>
                    <td class="text-center">{{ trial.hx }}</td>
                    <td class="text-center">{{ trial.sy }}</td>
                    <td class="text-center">{{ trial.sx }}</td>
                    <td class="text-center">
                        <button type="button" class="btn btn-outline-primary btn-sm"
                                onclick="doEditTrial({{ trial.id }});">
                            Edit
                        </button>&nbsp;
                        <form action="{% url 'trial-delete' trial.id %}" method="post" id="Trial-{{ trial.id }}-delete">
                            {% csrf_token %}
                            <button type="button" class="btn btn-outline-danger btn-sm"
                                    onclick='doConfirmDeleteSize({{ trial.id }}, {{ forloop.counter }});'>
                                Delete
                            </button>
                        </form>
                    </td>
                </tr>
                <tr id="Trial-{{ trial.id }}-Edit" hidden>
                    <form action="{% url 'trial-edit' trial.id %}" method="post" id="Trial-{{ trial.id }}-form">
                        {% csrf_token %}
                        <td class="text-center">{{ forloop.counter }}</td>
                        <td class="text-center">
                            <input type="number" id="Trial-{{ trial.id }}-hy" name="hy" value="{{ trial.hy }}"
                                   class="form-control">
                        </td>
                        <td class="text-center">
                            <input type="number" id="Trial-{{ trial.id }}-hx" name="hx" value="{{ trial.hx }}"
                                   class="form-control">
                        </td>
                        <td class="text-center">
                            <input type="number" id="Trial-{{ trial.id }}-sy" name="sy" value="{{ trial.sy }}"
                                   class="form-control">
                        </td>
                        <td class="text-center">
                            <input type="number" id="Trial-{{ trial.id }}-xs" name="sx" value="{{ trial.sx }}"
                                   class="form-control">
                        </td>
                        <td>
                            <button type="submit" class="btn btn-primary" form="Trial-{{ trial.id }}-form">
                                Save
                            </button>&nbsp;
                            <button type="reset" class="btn btn-secondary" form="Trial-{{ trial.id }}-form">
                                Reset
                            </button>&nbsp;
                            <button type="button" class="btn btn-secondary" form="Trial-{{ trial.id }}-form"
                                    onclick="doCancelEditTrial({{ trial.id }}, {{ forloop.counter }});">
                                Cancel</button>
                        </td>
                    </form>
                </tr>
                {% if forloop.last %}
                    <tr id="new_trial">
                        <td colspan="5">&nbsp;</td>
                {% endif %}
            {% empty %}
                <tr id="new_trial">
                    <td colspan="5">
                        <h4>None yet!</h4>
                    </td>
            {% endfor %}
                <td>
                    <button class="btn btn-primary" onclick="doNewTrial();">New Trial</button>
                </td>
            </tr>
            <tr id="Trial-New" hidden>
                <form action="{% url 'trial-new' %}" method="post" id="Trial-New-form">
                    {% csrf_token %}
                    <input type="hidden" id="Trial-New-fitSheet" name="fitSheet" value="{{ object.id }}"/>
                    <td>&nbsp;</td>
                    <td class="text-center">
                        <input type="number" id="Trial-New-hy" name="hy" value=""
                               class="form-control">
                    </td>
                    <td class="text-center">
                        <input type="number" id="Trial-New-hx" name="hx" value=""
                               class="form-control">
                    </td>
                    <td class="text-center">
                        <input type="number" id="Trial-New-sy" name="sy" value=""
                               class="form-control">
                    </td>
                    <td class="text-center">
                        <input type="number" id="Trial-New-xs" name="sx" value=""
                               class="form-control">
                    </td>
                    <td>
                        <span>
                            <button type="submit" class="btn btn-primary" form="Trial-New-form">
                                Save
                            </button>&nbsp;
                            <button type="reset" class="btn btn-secondary" form="Trial-New-form">
                                Reset
                            </button>&nbsp;
                            <button type="button" class="btn btn-secondary" form="Trial-New-form"
                                    onclick="doCancelNewTrial();">
                                Cancel</button>
                        </span>
                    </td>
                </form>
            </tr>
        </table>
    </div>
</div>

slowfit/templates/slowfit/fitsheet_new.html
{% extends "detail_form.html" %}

{% block Title %}
    New Fitsheet
{% endblock %}

{% block HeaderText %}
    New Fitsheet
{% endblock %}

slowfit/templates/slowfit/frame_detail_general.html
{% load field %}

<div class="card">
    <div class="card-body">
        {% field object "name" mode %}
        {% field object "description" mode %}
        {% field object "URL" mode %}
        {% field object "brand" mode %}
        {% field object "bikeType" mode %}
        {% field object "material" mode %}
        {% field object "yearFrom" mode %}
        {% field object "yearTo" mode %}
    </div>
</div>

slowfit/templates/slowfit/index.html
{% extends 'base.html' %}

{% block Title %}Slowfit bike fit tracker{% endblock %}

{% block Body %}
    {% if user is None or not user.is_authenticated %}
        <h3><a id="LoginLink" href="{% url "login" %}">You have to log in</a></h3>
    {% else %}
        <div>
            <h2>Find your frame</h2>
            <form name="fitcalculator">
                <div class="form-group">
                    <label for="HY">Handlebar Stack (HY):</label>
                    <input type="number" class="form-control" name="HY" id="HY" value="640"/>
                </div>
                <div class="form-group">
                    <label for="HX">Handlebar Reach (HX):</label>
                    <input type="number" class="form-control" name="HX" id="HX" value="514"/>
                </div>
                <div class="collapse" id="advanced">
                </div>
                <script>
                    function calculate() {
                        const hx = document.getElementById("HX").value;
                        const hy = document.getElementById("HY").value;
                        if (hx && hy) {
                            fetch(`{% url 'calculate' %}?hx=${hx}&hy=${hy}`)
                                .then((response) => {
                                    return response.json();
                                })
                                .then((data) => {
                                    if (data && data.length) {
                                        const table = document.getElementById("candidate-table");
                                        const body = table.tBodies[0];
                                        while (body.rows.length > 0) {
                                            body.deleteRow(0);
                                        }
                                        for (let i = 0; i < data.length; i++) {
                                            const row = data[i];
                                            const tr = body.insertRow();
                                            let td = tr.insertCell();
                                            td.className = "text-center";
                                            td.innerHTML = `<a href="/brand/${row.brand_id}">${row.brand}</a>`;
                                            td = tr.insertCell();
                                            td.className = "text-center";
                                            td.innerHTML = `<a href="/frame/${row.frame_id}">${row.frame}</a>`;
                                            td = tr.insertCell();
                                            td.className = "text-center";
                                            td.innerHTML = row.year_from;
                                            td = tr.insertCell();
                                            td.className = "text-center";
                                            td.innerHTML = row.frame_size;
                                            td = tr.insertCell();
                                            td.className = "text-center";
                                            td.innerHTML = row.spacers;
                                            td = tr.insertCell();
                                            td.className = "text-center";
                                            td.innerHTML = row.stem_length;
                                            td = tr.insertCell();
                                            td.className = "text-center";
                                            td.innerHTML = row.stem_angle;
                                            td = tr.insertCell();
                                            td.className = "text-center";
                                            const d = row.distance.toFixed(1);
                                            td.innerHTML = `${d}`;
                                        }
                                        const showCandidates = $('#show-candidates');
                                        showCandidates.collapse('show');
                                    }
                                });
                        }
                    }
                </script>
                <button type="button" class="btn btn-primary" onclick="calculate();">
                    Calculate Fit
                </button>
            </form>
            <div class="collapse" id="show-candidates">
                <div class="table-responsive">
                    <h2>Candidate Frames</h2>
                    <table class="table table-bordered table-hover" id="candidate-table">
                        <thead>
                            <tr>
                                <th class="text-center">Brand</th>
                                <th class="text-center">Frame</th>
                                <th class="text-center">Year</th>
                                <th class="text-center">Size</th>
                                <th class="text-center">Spacers (mm)</th>
                                <th class="text-center">Stem Length (mm)</th>
                                <th class="text-center">Angle (deg)</th>
                                <th class="text-center">Distance (mm)</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock Body %}

slowfit/templates/slowfit/visit_new.html
{% extends "detail_form.html" %}

{% block Title %}
    New Visit by {{ customer.fullname }}
{% endblock %}

{% block HeaderText %}
    New Visit by {{ customer.fullname }}
{% endblock %}