slowfit/models.py
from django.db import models
from django.contrib.auth.models import User
from time import datetime


class BaseModel(models.Model):
	name = models.CharField()
	description = models.TextField()


class Note(models.Model):
    posted  = models.DateTimeField(auto_now_add=True)
	noteFor = models.ForeignKey(BaseModel)
    by      = models.ForeignKey(User)
    text    = models.TextField()


def asset_directory(instance, filename):
	return f"assets/{instance.assetOf.name}"


class Asset(models.Model):
	assetOf     = models.ForeignKey(BaseModel)
	name        = models.CharField()
	description = models.TextField()
	tags        = models.TextField()
	mimeType    = models.TextField()
	asset       = models.FileField(upload_to=asset_directory)


class Country(models.Model):
	name     = models.CharField()
	isoCode  = models.CharField()
	isoCode3 = models.CharField()

    def flag(self, size):
        return f"/image/flags/{size}/{self.isoCode}.png"


class BikeType(BaseModel):
	pass


class Material(BaseModel):
	pass


class Brand(BaseModel):
	country     = models.ForeignKey(Country)
	URL         = models.URLField()
	imported    = models.ForeignKey(ImportLog)


class Frame(BaseModel):
	brand       = models.ForeignKey(Brand)
	bikeType    = models.ForeignKey(BikeType)
	material    = models.ForeignKey(Material)
	URL         = models.URLField()
	yearFrom    = models.PositiveSmallIntegerField()
	yearTo      = models.PositiveSmallIntegerField()
	imported    = models.ForeignKey(ImportLog)


class FrameSize(BaseModel):
	frame       = models.ForeignKey(Frame)
	HTAngle     = models.FloatField()

slowfit/templates/snippets/asset_tab.html
{% for asset in object.asset_set.all %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ asset.description|default:asset.name }}</h5>
                    <p class="card-text">Tags: {{ asset.tags }}</p>
                    <a href="/asset/{{ asset.id }}" class="card-link">Download</a>
                    <a href="/asset?action=delete&id={{ asset.id }}&redirect={{ request.path }}" class="card-link">Delete</a>
                </div>
                {% if asset.is_image %}
                   <img src="/asset/{{ asset.id }}" alt="{{ asset.name }}" class="card-img-bottom" width="600px"/>
                {% endif %}
            </div>
        </div>
    </div>
{% empty %}
    <div class="row my-3">
        <div class="col-sm-12">
            <h4>None yet!</h4>
        </div>
    </div>
{% endfor %}
<div class="row my-3">
    <div class="col-sm-12">
        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#upload-asset" aria-expanded="false" aria-controls="collapseExample">
            Upload File
        </button>
        <div class="collapse card" id="upload-asset">
            <div class="card-body">
                <h5 class="card-title">Upload File</h5>
                <form action="/asset" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="pid" value="{{ object.id}}"/>
                    <input type="hidden" name="pkind" value="{{ model }}"/>
                    <input type="hidden" name="update" value="false"/>
                    <div class="form-group">
                        <label for="Description">Description:</label>
                        <input type="text" class="form-control" name="Description"/>
                    </div>
                    <div class="form-group">
                        <label for="Tags">Tags:</label>
                        <input type="text" class="form-control" name="Tags" placeholder="Comma-separated"/>
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="data">File to upload</label>
                        <input type="file" name="data" class="form-control"/>
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Upload</button>
                </form>
            </div> <!-- card-body -->
        </div> <!-- collapse -->
    </div> <!-- col-sm-12 -->
</div> <!-- row -->

slowfit/templates/snippets/avatar.html
{% if object.avatar or avatar.fallback %}
    <div class="row my-3">
        <div class="col-sm-12">
            {% if object.avatar %}
                <a href="#" data-toggle="modal" data-target="#avatar-display">
                    <img width="200" src="/asset/{{ object.avatar.id }}" alt="{{ avatar.alt_text|default:"Avatar" }}"/>
                </a>
            {% else %}
                <img width="200" src="{{ avatar.fallback }}" alt="{{ avatar.alt_text|default:"Avatar" }}"/>
            {% endif %}
        </div>
    </div>
{% endif %}
{% if avatar.button_label %}
    <div class="row my-3">
        <div class="col-sm-12">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#upload-avatar"
                    aria-expanded="false" aria-controls="collapseExample">
                {{ avatar.button_label }}
            </button>
            <div class="collapse" id="upload-avatar">
                <div class="card card-body">
                    <form action="/asset" method="post" enctype="multipart/form-data" class="form-inline">
                        <input type="hidden" name="pid" value="{{ object.id }}"/>
                        <input type="hidden" name="pkind" value="{{ model }}"/>
                        <input type="hidden" name="update" value="true"/>
                        <input type="hidden" name="redirect" value="{{ request.path }}"/>
                        <input type="hidden" name="Tags" value="{{ avatar.tag }}"/>
                        <label class="sr-only" for="data">File</label>
                        <input type="file" name="data" class="form-control"/>
                        <button type="submit" class="btn btn-primary mb-2">Upload</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% if object.avatar %}
    <div class="modal fade" id="avatar-display" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <img src="/asset/{{ object.avatar.id }}" alt="{{ avatar.alt_text|default:"Avatar" }}"/>
            </div>
        </div>
    </div>
{% endif %}

slowfit/templates/snippets/field.html
{% if type == "TextField" %}
    {% if mode != "detail" %}
        <div class="form-group">
            <label for="{{ name }}">{{ field.verbose_name }}:</label>
            <textarea class="form-control" name="{{ name }}" id="{{ name}}"
                {% for attr in attrs %}
                    {{ attr }}="{{ attrs.attr }}"
                {% endfor %}
            >{{ value }}</textarea>
        </div>
    {% else %}
        <div class="row my-2">
            <div class="col-sm-4">{{ field.verbose_name }}:</div>
            <div class="col-sm-8"><pre>{{ value }}</pre></div>
        </div>
    {% endif %}
{% elif type == "ForeignKey" %}
    {% if mode != "detail" %}
        <div class="form-group" id="{{ name }}-Group">
            <label for="{{ name }}-Input">{{ field.verbose_name }}:</label>
        </div>
        <script>
            const {{ name }}Lookup = new Lookup(
                "{{ name }}-Group",
                {
                    name: "{{ name }}",
                    ref: "{{ attrs.referenceJSON }}",
                    query: "{{ attrs.query }}",
                    display: "`{{ attrs.displayExpr }}`"
                }
            );
        </script>
    {% else %}
        <div class="row my-2">
            <div class="col-sm-4">{{ field.verbose_name }}:</div>
            <div class="col-sm-8"><a href="{{ attrs.href }}">{{ value }}</a></div>
        </div>
    {% endif %}
{% else %}
    {% if mode != "detail" %}
        <div class="form-group">
            <label for="{{ name }}">{{ field.verbose_name }}:</label>
            {% if "options" in attrs %}
                <datalist id="{{ name }}-Datalist">
                    {% for option in args.options %}
                        <option>{{ option }}</option>
                    {% endfor %}
                </datalist>
            {% endif %}
            <input type="{{ inputtype }}" class="form-control" name="{{ name }}" id="{{ name }}" value="{{ value }}"
                {% for attr in attrs %}
                    {% if attr == "options" %}
                        list="{{ name }}-Datalist"
                    {% elif attr == "href" %}
                    {% else %}
                        {{ attr }}="{{ attrs.attr }}"
                    {% endif %}
                {% endfor %}
            />
        </div>
    {% else %}
        <div class="row my-2">
            <div class="col-sm-4">
                {{ field.verbose_name }}:
            </div>
            <div class="col-sm-8" id="{{ name }}">
                {% if "href" in attrs %}
                    <a href="{{ attrs.href }}">{{ value }}</a>
                {% else %}
                    {% if type == "URLField" %}
                        {{ value|urlize }}
                    {% else %}
                        {{ value }}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endif %}

slowfit/templates/snippets/notes_tab.html
{% load humanize %}

{% for note in object.note_set.all %}
    <div class="row my-3">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ note.posted|naturaltime }}
                        <small>
                            {% if note.author %}
                                {{ note.author.first_name }}{{ note.author.last_name }}
                            {% else %}
                                Anonymous
                            {% endif %}
                        </small>
                    </h5>
                    <p class="card-text">{{ note.text }}</p>
                    <a href="/note?action=delete&id={{ note.id }}&redirect={{ request.path }}" class="card-link">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% empty %}
    <div class="row my-3">
        <div class="col-sm-12">
            <h4>None yet!</h4>
        </div>
    </div>
{% endfor %}
<div class="row my-3">
    <div class="col-sm-12">
        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#add-note" aria-expanded="false" aria-controls="collapseExample">
            Add Note
        </button>
        <div class="collapse card" id="add-note">
            <div class="card-body">
                <h5 class="card-title">Add Note</h5>
                <form action="/note" method="post">
                    <input type="hidden" name="pid" value="{{ object.id }}"/>
                    <input type="hidden" name="pkind" value="{{ model}}"/>
                    <input type="hidden" name="redirect" value="{{ request.path }}"/>
                    <div class="form-group">
                        <label for="Text">Note:</label>
                        <textarea class="form-control" name="Text" id="Text" rows="5" cols="50"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Add</button>
                </form>
            </div> <!-- card-body -->
        </div> <!-- collapse -->
    </div> <!-- col-sm-12 -->
</div> <!-- row -->

slowfit/templates/snippets/tabheader.html
<li class="nav-item">
    <a class="nav-link {{ tab_class}}" id="{{ tab_id }}-tab"
       data-toggle="tab" href="#{{ tab_id }}" role="tab"
       aria-controls="profile" aria-selected="true">{{ tab_label }}</a>
</li>